# Generated by Django 2.1.3 on 2020-03-15 18:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Acta Pasajeros'), (2, 'Informe Externo'), (3, 'Informe Particular'), (4, 'Denuncia Externo')], default='1')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombres')),
                ('archivo', models.FileField(upload_to='informacion/', verbose_name='Archivo')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del evento')),
                ('procesado', models.BooleanField(default=False)),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos', to='operadores.Operador')),
            ],
        ),
        migrations.CreateModel(
            name='Individuo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_doc', models.IntegerField(choices=[(1, 'CI'), (2, 'DNI'), (3, 'LC'), (4, 'LE'), (5, 'Pasaporte')], default=2)),
                ('num_doc', models.IntegerField(unique=True, verbose_name='Numero de Documento/Pasaporte')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('telefono', models.CharField(blank=True, default='+549388', max_length=20, null=True, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electronico')),
                ('nacionalidad', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('origen', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('destino', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('particularidades', tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individuo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origenes', to='informacion.Individuo')),
            ],
        ),
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del Registro')),
                ('aclaracion', models.CharField(max_length=200, verbose_name='Aclracion')),
                ('individuo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sintomas', to='informacion.Individuo')),
            ],
        ),
        migrations.CreateModel(
            name='TipoSintoma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', tinymce.models.HTMLField(verbose_name='Plan de Ruta')),
                ('importancia', models.IntegerField(choices=[(1, 'Particular'), (2, 'Colectivo'), (3, 'Traffic'), (4, 'Comercial Pequeño'), (5, 'Avion')], default='1')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Particular'), (2, 'Colectivo'), (3, 'Traffic'), (4, 'Comercial Pequeño'), (5, 'Avion')], default='1')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del Registro')),
                ('identificacion', models.CharField(max_length=200, verbose_name='Identificacion Patente/Codigo')),
                ('cant_pasajeros', models.IntegerField(default='1')),
                ('empresa', models.CharField(blank=True, max_length=200, null=True, verbose_name='Empresa (Si aplica)')),
                ('plan', tinymce.models.HTMLField(verbose_name='Plan de Ruta')),
            ],
        ),
        migrations.AddField(
            model_name='origen',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origenes', to='informacion.Vehiculo'),
        ),
    ]
