# Generated by Django 2.1.3 on 2020-03-15 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('informacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sintoma',
            name='sintoma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sintomas', to='informacion.TipoSintoma'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='archivo',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Acta Pasajeros'), (2, 'Informe Externo'), (3, 'Informe Particular'), (4, 'Denuncia')], default='1'),
        ),
    ]
