# Generated by Django 2.1.3 on 2020-03-15 17:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('cuerpo', tinymce.models.HTMLField()),
                ('tipo', models.IntegerField(choices=[(1, 'Asistencia'), (2, 'Operativa'), (3, 'Parte Comunicacion')], default=5)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del Acta')),
                ('publica', models.BooleanField(default=False, verbose_name='Publicable')),
            ],
        ),
        migrations.CreateModel(
            name='EventoParticipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Ingreso'), (2, 'Egreso')], default=1)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='Participes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participes', to='actas.Acta')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participes', to='operadores.Operador')),
            ],
        ),
        migrations.AddField(
            model_name='eventoparticipe',
            name='participe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='actas.Participes'),
        ),
    ]
