# Generated by Django 2.1.3 on 2020-03-15 16:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.IntegerField(choices=[(1, 'Ingreso'), (2, 'Modificacion'), (3, 'Retiro')], default='1')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del evento')),
                ('detalle', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('situacion', tinymce.models.HTMLField()),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proveedor_items', to='operadores.Operador')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsable_items', to='operadores.Operador')),
            ],
        ),
        migrations.AddField(
            model_name='eventoitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='inventario.Item'),
        ),
        migrations.AddField(
            model_name='eventoitem',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='operadores.Operador'),
        ),
    ]
