TIPO_PROFESIONAL = (
    (1, 'Enfermeros profesionales'),
    (11, 'Auxiliares de enfermería'),
    (12, 'Licenciados de enfermería'),
    (2, 'Médicos de todas las especialidades'),
    (21, 'Técnicos radiólogos'),
    (22, 'Técnicos de farmacia'),
    (3, 'Farmacéuticos'),
    (4, 'Técnicos en emergencia'),
    (5, 'Técnicos de laboratorio'),
    (6, 'Bioquímicos'),
    (7, 'Kinesiólogos especializados en pacientes respiratorios'),
    (81, 'Educadores de la salud'),
    (82, 'Trabajador Social'),
    (91, 'Psicologos'),
    (92, 'Psiquiatra'),
    (99, 'Estudiantes de Carreras de Ciencias de la Salud'),
)