COLOR_RESTRICCION = (
    ('B', 'Blanco (Normalidad)'),
    ('V', 'Verde (Minima)'),
    ('A', 'Amarillo (Intermedia)'),
    ('R', 'Rojo (Maxima)'),
    ('D', 'Permisos Digitales Desactivados'),
)

GRUPOS_PERMITIDOS = (
    (0, 'No se Autoriza a Nadie'),
    (1, 'Todos los DNI diariamente'),
    (2, 'Division por Pares e Impares'),
    (3, 'Tres Grupos: 1,2,3 - 4,5,6 - 7,8,9,0'),
    (5, 'Cinco Grupos: 1,2 - 3,4 - 5,6 - 7,8 - 9,0'),
)

TIPO_PERMISO = (
    ('C', 'Compras de Primera Necesidad'),
    ('F', 'Compras de Farmacia'),
    ('B', 'Turno Bancario'),
    ('R', 'Responsable de Personas a Cargo'),
    ('P', 'Permiso Permanente'),
)

TIPO_INGRESO = (
    ('P', 'Particular en Vehiculo Propio'),
    ('T', 'Taxi/Remis Contratado'),
    ('C', 'Colectivo (Carga la Empresa)'),
    ('A', 'Aereo (Carga la Empresa)'),
)

ESTADO_INGRESO = (
    ('C', 'Cargando Pedido'),
    ('E', 'Pedido Cargado'),
    ('N', 'Esperando Aprobacion de Nacion'),
    ('A', 'Aprobado'),
    ('B', 'Dado de Baja'),
)

TIPO_ACTIVIDAD = (
    (1, 'Transporte de Carga'),
    (2, 'Taxi/Remis'),
    (3, 'Trabajado Interprovincial Exceptuado (Salta-Jujuy)'),
    (4, 'Transito Provincial (Sin escala en la provincia)'),
    (5, 'Tramite Excepcional en el Dia (Salta-Jujuy)'),
    
    # (1, 'Personal de Salud, Fuerzas de seguridad, Fuerzas Armadas, actividad Migratoria, Servicio Meteorológico Nacional, Bomberos y Control de tráfico aéreo.'),
    # (2, 'Trabajadores del sector público nacional, provincial, municipal, convocados para garantizar actividades esenciales requeridas por las respectivas autoridades.'),
    # (3, 'Personal de los servicios de justicia de turno, conforme establezcan las autoridades competentes.'),
    # (4, 'Personal diplomático y consular extranjero acreditado ante el gobierno argentino, de la Cruz Roja y Cascos Blancos.'),
    # (5, 'Personas que deban asistir a otras con discapacidad o familiares que necesiten asistencia.'),
    # (6, 'Personas que deban atender una situación de fuerza mayor.'),
    # (7, 'Personas afectadas a la realización de servicios funerarios, entierros y cremaciones.'),
    # (8, 'Personas afectadas a la atención de comedores escolares, comunitarios y merenderos.'),
    # (9, 'Personal que se desempeña en los servicios de comunicación audiovisuales, radiales y gráficos.'),
    # (10, 'Personal afectado a obra pública.'),
    # (11, 'Supermercados mayoristas y minoristas y comercios minoristas de proximidad. Farmacias. Ferreterías. Veterinarias. Provisión de garrafas.'),
    # (12, 'Industrias de alimentación, su cadena productiva e insumos; de higiene personal y limpieza; de equipamiento médico, medicamentos, vacunas y otros insumos sanitarios.'),
    # (13, 'Actividades vinculadas con la producción, distribución y comercialización agropecuaria y de pesca.'),
    # (14, 'Actividades de telecomunicaciones, internet fija y móvil y servicios digitales.'),
    # (15, 'Actividades impostergables vinculadas con el comercio exterior.'),
    # (16, 'Recolección, transporte y tratamiento de residuos sólidos urbanos, peligrosos y patogénicos.'),
    # (17, 'Mantenimiento de los servicios básicos (agua, electricidad, gas, comunicaciones, etc.) y atención de emergencias.'),
    # (18, 'Transporte público de pasajeros, transporte de mercaderías, petróleo, combustibles y GLP.'),
    # (19, 'Reparto a domicilio de alimentos, medicamentos, productos de higiene, de limpieza y otros insumos de necesidad.'),
    # (20, 'Servicios de lavandería.'),
    # (21, 'Servicios postales y de distribución de paquetería.'),
    # (22, 'Servicios esenciales de vigilancia, limpieza y guardia.'),
    # (23, 'Guardias mínimas que aseguren la operación y mantenimiento de Yacimientos de Petróleo y Gas, plantas de tratamiento y/o refinación de Petróleo y gas, transporte y distribución de energía eléctrica, combustibles líquidos, petróleo y gas, estaciones expendedoras de combustibles y generadores de energía eléctrica.'),
    # (24, 'Casa de Moneda, servicios de cajeros automáticos, transporte de caudales y todas aquellas actividades que el BANCO CENTRAL DE LA REPÚBLICA ARGENTINA disponga imprescindibles.'),
)

FRONTERA_CONTROL = (
    (1, "Pampa Blanca"),
    (2, "Rio Piedras"),
    (3, "Puesto del Marques"),
    (4, "La estrella"),
    (5, "Jama"),
    (10, "Leon"),
)

TIPO_ALARMA = (
    ('SA', "Sin Alarmas"),
    ('TE', "Tiempo Excedido"),
    ('DP', "Diferencia de Pasajeros"),
    ('SS', "Sin Salida a tiempo"),
)

COMBINACION_DNIxDIA = (
    ('0-0', 'Lunes Habilitada Terminacion: 0'),
    ('0-1', 'Lunes Habilitada Terminacion: 1'),
    ('0-2', 'Lunes Habilitada Terminacion: 2'),
    ('0-3', 'Lunes Habilitada Terminacion: 3'),
    ('0-4', 'Lunes Habilitada Terminacion: 4'),
    ('0-5', 'Lunes Habilitada Terminacion: 5'),
    ('0-6', 'Lunes Habilitada Terminacion: 6'),
    ('0-7', 'Lunes Habilitada Terminacion: 7'),
    ('0-8', 'Lunes Habilitada Terminacion: 8'),
    ('0-9', 'Lunes Habilitada Terminacion: 9'),
    ('1-0', 'Martes Habilitada Terminacion: 0'),
    ('1-1', 'Martes Habilitada Terminacion: 1'),
    ('1-2', 'Martes Habilitada Terminacion: 2'),
    ('1-3', 'Martes Habilitada Terminacion: 3'),
    ('1-4', 'Martes Habilitada Terminacion: 4'),
    ('1-5', 'Martes Habilitada Terminacion: 5'),
    ('1-6', 'Martes Habilitada Terminacion: 6'),
    ('1-7', 'Martes Habilitada Terminacion: 7'),
    ('1-8', 'Martes Habilitada Terminacion: 8'),
    ('1-9', 'Martes Habilitada Terminacion: 9'),
    ('2-0', 'Miercoles Habilitada Terminacion: 0'),
    ('2-1', 'Miercoles Habilitada Terminacion: 1'),
    ('2-2', 'Miercoles Habilitada Terminacion: 2'),
    ('2-3', 'Miercoles Habilitada Terminacion: 3'),
    ('2-4', 'Miercoles Habilitada Terminacion: 4'),
    ('2-5', 'Miercoles Habilitada Terminacion: 5'),
    ('2-6', 'Miercoles Habilitada Terminacion: 6'),
    ('2-7', 'Miercoles Habilitada Terminacion: 7'),
    ('2-8', 'Miercoles Habilitada Terminacion: 8'),
    ('2-9', 'Miercoles Habilitada Terminacion: 9'),
    ('3-0', 'Jueves Habilitada Terminacion: 0'),
    ('3-1', 'Jueves Habilitada Terminacion: 1'),
    ('3-2', 'Jueves Habilitada Terminacion: 2'),
    ('3-3', 'Jueves Habilitada Terminacion: 3'),
    ('3-4', 'Jueves Habilitada Terminacion: 4'),
    ('3-5', 'Jueves Habilitada Terminacion: 5'),
    ('3-6', 'Jueves Habilitada Terminacion: 6'),
    ('3-7', 'Jueves Habilitada Terminacion: 7'),
    ('3-8', 'Jueves Habilitada Terminacion: 8'),
    ('3-9', 'Jueves Habilitada Terminacion: 9'),
    ('4-0', 'Viernes Habilitada Terminacion: 0'),
    ('4-1', 'Viernes Habilitada Terminacion: 1'),
    ('4-2', 'Viernes Habilitada Terminacion: 2'),
    ('4-3', 'Viernes Habilitada Terminacion: 3'),
    ('4-4', 'Viernes Habilitada Terminacion: 4'),
    ('4-5', 'Viernes Habilitada Terminacion: 5'),
    ('4-6', 'Viernes Habilitada Terminacion: 6'),
    ('4-7', 'Viernes Habilitada Terminacion: 7'),
    ('4-8', 'Viernes Habilitada Terminacion: 8'),
    ('4-9', 'Viernes Habilitada Terminacion: 9'),
    ('5-0', 'Sabado Habilitada Terminacion: 0'),
    ('5-1', 'Sabado Habilitada Terminacion: 1'),
    ('5-2', 'Sabado Habilitada Terminacion: 2'),
    ('5-3', 'Sabado Habilitada Terminacion: 3'),
    ('5-4', 'Sabado Habilitada Terminacion: 4'),
    ('5-5', 'Sabado Habilitada Terminacion: 5'),
    ('5-6', 'Sabado Habilitada Terminacion: 6'),
    ('5-7', 'Sabado Habilitada Terminacion: 7'),
    ('5-8', 'Sabado Habilitada Terminacion: 8'),
    ('5-9', 'Sabado Habilitada Terminacion: 9'),
    ('6-0', 'Domingo Habilitada Terminacion: 0'),
    ('6-1', 'Domingo Habilitada Terminacion: 1'),
    ('6-2', 'Domingo Habilitada Terminacion: 2'),
    ('6-3', 'Domingo Habilitada Terminacion: 3'),
    ('6-4', 'Domingo Habilitada Terminacion: 4'),
    ('6-5', 'Domingo Habilitada Terminacion: 5'),
    ('6-6', 'Domingo Habilitada Terminacion: 6'),
    ('6-7', 'Domingo Habilitada Terminacion: 7'),
    ('6-8', 'Domingo Habilitada Terminacion: 8'),
    ('6-9', 'Domingo Habilitada Terminacion: 9'),
)
