# Generated by Django 2.1.3 on 2020-03-15 16:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoTarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.IntegerField(choices=[(1, 'Creacion'), (2, 'Modificacion'), (3, 'Avance'), (4, 'Cancelacion'), (5, 'Finalizacion')], default='1')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del evento')),
                ('detalle', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Asignacion')),
                ('obligaciones', tinymce.models.HTMLField()),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='operadores.Operador')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', tinymce.models.HTMLField()),
                ('prioridad', models.IntegerField(choices=[(1, 'Critica'), (2, 'Alta'), (3, 'Normal'), (4, 'Baja'), (5, 'Opcional')], default=5)),
                ('begda', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Inicio')),
                ('endda', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Limite')),
            ],
        ),
        migrations.AddField(
            model_name='eventotarea',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='tareas.Responsable'),
        ),
        migrations.AddField(
            model_name='eventotarea',
            name='tarea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='tareas.Tarea'),
        ),
    ]
