# Generated by Django 2.1.3 on 2020-03-14 19:38

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100, verbose_name='Nombre y Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electronico Personal')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefono')),
                ('asunto', models.CharField(max_length=100, verbose_name='Asunto')),
                ('descripcion', tinymce.models.HTMLField()),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('valida', models.BooleanField(default=False, verbose_name='Email Validado')),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('pregunta', models.CharField(max_length=200, verbose_name='Titulo')),
                ('respuesta', tinymce.models.HTMLField()),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
